### ISSUE TITLE
Add simple_math directory with a Cairo script with arithmetic operations

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#15]
## Description
- We want to have a similar directory like the `hello_world` but called `simple_math`
- This directory should hold a cairo file that performs simple math operations and print results
- Follow this [guide](https://book.cairo-lang.org/ch01-02-hello-world.html) to replicate the work done in the `hello_world` directory.

**Comment by derianrddev** [comment]
Hi, I'm Derian, I'm a software engineer focused on fullstack web development and I'm currently part of Dojo Coding. I have been studying Cairo through the Starknet Bootcamp, completed all the Starklings exercises, and have been practicing on Node Guardians. I would like to work on this issue and gain more experience.
