### ISSUE TITLE
Add instructions about how to run the Cairo Scripts

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#16]
## Description
- Add in the README a section about how to build and run the Cairo Scripts
- Follow this [guide](https://book.cairo-lang.org/ch01-02-hello-world.html)

**Comment by DiegoB1911** [comment]
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I'm enthusiastic about learning, and becoming a part of this project.

To address this issue, I would take the following steps:

1. Review the Project Scripts: I will analyze the existing Cairo scripts to understand their structure, dependencies, and functionality.

2. Consult the Documentation Guide: I will follow the provided guide to ensure that I include all necessary details in the README.

3. Verify Execution Steps: I will run the Cairo scripts myself to confirm that the documented steps are accurate and functional.

4. Draft README Instructions: I will create a clear and concise section in the README that outlines how to build and run the Cairo scripts.

**Comment by danielcdz** [comment]
@DiegoB1911 any updates here?

**Comment by DiegoB1911** [comment]
Sorry for the delay. I’ll create the PR by tomorrow
