### ISSUE TITLE
Fix and Implement hello_world contract

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#19]
## Summary
- Delete hello_world directory
- Create a new hello_world directory with a simple contract
- This contract should be compiled using scarb 2.8.4
- Use Starknet Foundry  0.32.0
- The smart contract should perform a simple read call that returns a Hello world Message with the caller address
- Add unit tests

**Comment by Gerson2102** [comment]
Can I work on it?

**Comment by danielcdz** [comment]
@Gerson2102 all yours
