### ISSUE TITLE
Create smart contract with events

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#21]
## Description
- We want an example of a simple smart contract that emits events once an action is performed.
- Feel free to propose the smart contract structure and methods, It doesn't need to be a complex contract, with a couple of events and methods is good.

## Steps
- Create a new smart contract inside the project's corresponding directory.

## References
- https://book.cairo-lang.org/ch14-03-contract-events.html?highlight=events#defining-events

**Comment by Chukwuemeka-James** [comment]
@danielcdz 

I can handle the above task.
if assigned I would implement and test all emited events work as i have some experience writing smart contract and writing test for smart contracts

**Comment by SoarinSkySagar** [comment]
May I work on this issue @danielcdz?

My approach: I will create a new contract that emits events once the functions are called, and then write unit tests too to make sure events are being emitted as expected

eta: 1 day

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with experience contributing to lots of Cairo projects. I would love to work on this.

**Comment by mimisavage** [comment]
Can I attempt this issue?

**Comment by GideonBature** [comment]
I’d love to work on this task.

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by Benjtalkshow** [comment]
I’d love to work on this task.

**Comment by mimiprosper** [comment]
Can I take this issue?   Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You
