### ISSUE TITLE
Test smart contract events

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#22]
## Description
- We want to have an example of how to test the events emitted by a contract.

## Steps
- Add a test file to check if the smart contract events are emitted properly.

## References
- https://foundry-rs.github.io/starknet-foundry/testing/testing-events.html

## Dependencies
- This issue can be worked on after #21 is completed.

**Comment by martinvibes** [comment]
Hey @danielcdz can I work on this issue when the Od hack starts

**Comment by codeZe-us** [comment]
Will write a basic test for events emitted by a contract. 
ETA: 2 hours.

**Comment by omsant02** [comment]
Can I be assigned to this?

**Comment by SoarinSkySagar** [comment]
can i take up this issue @danielcdz ?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by GideonBature** [comment]
I’d like to help with this.

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by Birdmannn** [comment]
Please is this issue still available, can I go on ahead with it, or suggest other issues?
I graduated from the recent cairo bootcamp batch and I've studied the cairo book and the starknet books extensively. I would sincerely like to give back to the community as what the community has impacted on me.

**Comment by Benjtalkshow** [comment]
Can I work on this, please?

**Comment by juandiegocv27** [comment]
Can I contribute to this one?

**Comment by wheval** [comment]
I'd be happy to do this. Please assign.

**Comment by MullerTheScientist** [comment]
can i please tackle this task

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects etc  .   please /assign  this issue .
Thank You

**Comment by mimiprosper** [comment]
May I handle this issue?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by morelucks** [comment]
Is it okay if I tackle this?

**Comment by Benjtalkshow** [comment]
@danielcdz 
I wanna let you know that i am still working on this. Thanks
