### ISSUE TITLE
Move hello_world contract to its directory

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#23]
## Description
- The current sample of the hello_world contract is in `cairo/scripts`, this contract needs to be moved to the contracts directory.

## Steps
- Move the contract to the correct directory.
- Leave a simple hello_world script in `cairo/scripts`.

**Comment by gusata** [comment]
Hello, can I work on this? @danielcdz

**Comment by codeZe-us** [comment]
Can I handle this task?
ETA: 5 minutes

**Comment by omsant02** [comment]
I'd love to give this a go.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I be assigned to this?
To solve this issue,I will move the hello_world contract from the cairo/scripts directory to the contracts directory.  Thereby ensuring that the contract remains functional after the move. 
Then,  i will leave a simple placeholder hello_world script in the cairo/scripts directory, which can either be a minimal version or a reference to the contract in the contracts directory.

**Comment by Benjtalkshow** [comment]
I'd love to work on this!

**Comment by Thibrac** [comment]
Hi ! I would like to take this path to continue to progress in Cairo and in project management :)

**Comment by juandiegocv27** [comment]
Would love to tackle this!

**Comment by wheval** [comment]
Could I take on this issue? This is pretty straightforward and would be my first contribution to this repo.

I can do this in 1 day, please assign. Thank you!

**Comment by Michaelkingsdev** [comment]
Can I take this from here?

**Comment by mimiprosper** [comment]
I’d love to work on this task. Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You
