### ISSUE TITLE
Add steps to build and run tests for Starknet Contracts

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#24]
## Description
- Currently, the README only has instructions for running Cairo scripts, we want to have the same for the contracts.

## Steps
- Add build instructions 
- Add tests instructions
- Have in mind that we are using starknet-foundry

## References
- https://foundry-rs.github.io/starknet-foundry/index.html

**Comment by vestor-dev** [comment]
Holla @danielcdz would love to handle this task by the time odhack begins :)

**Comment by omsant02** [comment]
May I pick this up?

**Comment by codeZe-us** [comment]
Will add build and test instructions for contracts.
ETA: 2 hours.

**Comment by SoarinSkySagar** [comment]
May I work on this issue @danielcdz?

**Comment by gchimelu** [comment]
hello,
I would love to be assigned to work on this. I am a technical writer with experience in simplifying processes and products in Web3. With my expertise, I can help you add clear and concise instructions for how to build and run tests on contracts, to your documentation.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by mimisavage** [comment]
Can I try solving this issue?

**Comment by Benjtalkshow** [comment]
May I handle this issue?

**Comment by Iwueseiter** [comment]
Could I takI'm a frontend/smart contract developer and a technical writer.
Here are links to comprehensive docs I've written and have been merged Flex-NFT-Marketplace/Flex-Marketplace-Contract#107, https://github.com/cairo-book/cairo-book/pull/1019, https://github.com/horuslabsio/tokenbound-contract-docs/pull/12, https://github.com/sivicstudio/starkludo/pull/102, https://hackmd.io/@-__sK8xkRjuXHkFZQLyYXg/HkLcMImM1l.

I will update the readme  to capture build instructions
and tests instructions .

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario would love to work on this , my ETA is >4 Hours and ill create a draft PR in 2 hours time. Thank you for this opportunity. :)

**Comment by MullerTheScientist** [comment]
I'd love to address this issue

**Comment by gchimelu** [comment]
Thanks for assigning this to me! Starting work ASAP 🤝
