### ISSUE TITLE
Create counter contract

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#25]
## Description
- One of the famous examples of a simple contract is a counter contract, which allows users to increment, decrement, or reset a counter value stored on the blockchain. It is a foundational example of understanding how to write, deploy, and interact with smart contracts.

## Steps
- Add a new simple counter contract in the corresponding directory.

**Comment by mayasimi** [comment]
Hi @danielcdz kindly assign me i just finished cairo boot camp and have some experience writing smart contracts using cairo and i believe this task would help me solidify my understanding. Kindly assign me if avaliable

steps to solve the above task:
1. I need to implement the following:
- A storage variable to hold my counter value
- Public functions to manipulate this value
- Events to track changes

2. I'll need these main functions:
a) Constructor:
   - Initialize my counter to 0
   - Set up any initial state

b) get_counter():
   - Let me read current counter value
   
c) increment():
   - Add 1 to current value
   
d) decrement():
   - Subtract 1 from current value
   
e) reset():
   - Set counter back to 0
   
   
  3. I'll emit events for:
- Counter incremented (new value)
- Counter decremented (new value)
- Counter reset

4. I'll test:
- Initial value is 0
- Increment works
- Decrement works
- Reset works
- Multiple operations work correctly

ETA <= 15hrs

**Comment by codeZe-us** [comment]
Will be achieved by writing a CounterContract with owner only access control implementation with unit testing. 
ETA: 4 hours.

**Comment by codeZe-us** [comment]
Could I take on this issue?
ETA: 3 Hours.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by mimisavage** [comment]
Could I be assigned to this?

**Comment by Unickhub** [comment]
I’d like to help with this.

**Comment by ShantelPeters** [comment]
Can I take this issue?

 I will start by creating a simple counter contract in the specified directory that stores a counter value and provides methods to increment, decrement, and reset the counter. Then i will Include a get_counter function to retrieve the current counter value, ensuring the contract is straightforward and well-documented.

**Comment by ChrisFernandezVivas** [comment]
hi , im fron dojo coding

steps

1- declare mi smart contract counter

2 - declare my 3 functions (increment, decrement, reset)

3- deply tha contract and testing if works well 

thank you

**Comment by NueloSE** [comment]
I’d like to resolve this.

i have experience in writing and testing smart contracts

**Comment by MullerTheScientist** [comment]
hello please can i address this issue

**Comment by wheval** [comment]
Can I take care of this issue? I have built this contract before, and would love to contribute  to this repo. I would also write test for the contract and ensure they pass.
Please assign.
ETA is 1 day. Thank you.

**Comment by Michaelkingsdev** [comment]
Could I take a shot at this?

**Comment by mimiprosper** [comment]
I'd love to give this a go.  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
Thank you @danielcdz
