### ISSUE TITLE
Create a FlipFlop contract

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#27]
## Description
- Add a basic flip-flop contract that manages the state of a boolean variable stored on-chain. The contract includes methods to toggle the state and retrieve the current value, providing a simple example of state management and interaction in a smart contract.
- Add the contract to its corresponding directory.

**Comment by petersdt** [comment]
Let me try this one!

**Comment by aradix16** [comment]
Hello im Antoine from Santiago :)
I'm currently learning Cairo and I think contributing to this project could be an nice opportunity for me to learn by doing. I participated to the flip-flop  challenge few days ago so it would be cool to implement it.

I recently attended a Starknet bootcamp at my school (42 Paris) and since then, I've completed all the Starklings exercises and some Node Guardians quests. I'm still pretty new to Cairo but I'm super motivated to level up my skills quickly.

**Comment by omsant02** [comment]
Could I take on this issue?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by 0xprivateChaos** [comment]
Hi, I'm Aman, and I'd like to work on this issue.

My plan would be:
1. Implement a ```toggle()``` function to flip the boolean state
2. Create a ```get_state()``` view function to retrieve the current state
3. Include a constructor to initialize the default state

**Comment by ShantelPeters** [comment]
May I pick this up?

Firstly i will create a flip-flop contract that stores a boolean state on-chain, with a toggle method to change the state and a get_state method to retrieve the current value. Thereby ensuring the contract demonstrates basic state management and interaction, then add it to the appropriate directory.

**Comment by Benjtalkshow** [comment]
Let me try this one!

**Comment by KevinMB0220** [comment]
Hi, I’m Kevin, part of Dojo Coding. I’d like to work on this issue to learn more about Cairo and put it into practice. I plan to approach this by implementing a basic Flip-Flop contract that manages a boolean state on-chain, including methods to toggle and retrieve the state. I’ll ensure the solution is simple, efficient, and follows best practices for smart contract development in Cairo

**Comment by mimiprosper** [comment]
Is this issue still available?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You
