### ISSUE TITLE
Create a Counter Contract but with access control

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#28]
## Description
- We want to have an example of access control to some methods, this can be done with a simple CounterContract.

## Steps
- Create a CounterContract 
- Add access control to the methods so that the owner of the contract can call them.
- Add unit tests.

**Comment by codeZe-us** [comment]
Will be achieved by writing a CounterContract with owner only access control implementation with unit testing. 
ETA: 4 hours.

**Comment by omsant02** [comment]
Could I grab this task?

**Comment by SoarinSkySagar** [comment]
May I work on this issue @danielcdz?

I will create a new CounterContract and then modify the code so that only the owner can call its functions. I will also add unit tests and make sure everything passes.

ETA: 1 day

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer and I have the opportunity to implement access control in previous projects.

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by Benjtalkshow** [comment]
Can I tackle this one?

**Comment by Michaelkingsdev** [comment]
May I take this issue on?

**Comment by mimiprosper** [comment]
Is it okay if I tackle this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.
