### ISSUE TITLE
Check even or odd in Cairo

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#29]
## Description
- We want to have a dedicated script in Cairo that checks if a number is even or odd in Cairo.

## Steps
- Add a new script in the dedicated scripts directory

**Comment by petersdt** [comment]
@danielcdz kindly assign me this issue when ODhack10 starts

i experience in writing smart contracts and writing test for smart contracts
a pseduo approach to the above would be as following:

1. I'll create a function called 'check_even_odd' that takes a u256 number as input
2. I'll use Cairo's modulo operator (%) to divide by 2 and check remainder: number % 2 will give me either 0 or 1
3. for return value, I'll return a boolean: 
   - true for even
   - false for odd
 4. I'll create test cases to verify: 
 - I'll test with 0 (should be even)
- I'll test with 1 (should be odd)
- I'll test with some larger numbers
5. error handling:

I'll need to consider:
- How I want to handle negative numbers
- Any potential overflow cases for very large numbers

**Comment by Emrys02** [comment]
Hi @danielcdz my approach would be to use the modulo operator to determine if the input is even or odd then return an appropriate boolean

**Comment by SoarinSkySagar** [comment]
May I work on this issue @danielcdz?

**Comment by omsant02** [comment]
I'd love to work on this!

**Comment by codeZe-us** [comment]
Will write a script that checks if a number is even or odd. 
ETA: 2 hours.

**Comment by Emmanex01** [comment]
Can I start working on this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Thibrac** [comment]
Hi, I'm level 6 on NG, I would do this issue if possible :)

**Comment by mimisavage** [comment]
Let me try this one!

**Comment by aurlic** [comment]
Hey ! I would love to work on this issue to put my newly acquired skill to the test. I am currently learning with NodeGuardians and think I could handle this. Thanks in advance !

**Comment by GideonBature** [comment]
I’d like to work on this.

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by Unickhub** [comment]
Can I start working on this?

**Comment by Benjtalkshow** [comment]
I’d like to work on this.

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario, would love to work on this , my ETA is >5 Hours and ill create a draft PR in 4 hours time. Thank you for this opportunity. :)

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You
