### ISSUE TITLE
Fibonacci in Cairo

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#30]
## Description
- Create a script in Cairo that calculates the Fibonacci of a given number.

## Steps
- Add the new script in the scripts directory.

**Comment by Kingsuite** [comment]
@danielcdz I just finished a cairo bootcamp and am looking for opportunities to contribute to the starknet eco system and i feel this is an opportunity for me to leverage all i learnt during the bootcamp kindly assign me the above task 

ETA <= 24hrs

**Comment by Emrys02** [comment]
Hi @danielcdz I have been practicing a lot of leetcode problems and would be able to share a solution within an hour should I get the task.

**Comment by codeZe-us** [comment]
Will be achieved by writing Fibonacci calculation in Cairo using a simple iterative approach. 
ETA: 1 hour.

**Comment by omsant02** [comment]
May I take this issue on?

**Comment by Thibrac** [comment]
Hello i need my first issue for begin, thank you for your attention !

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by mimisavage** [comment]
I’d love to work on this task.

**Comment by GideonBature** [comment]
May I try my hand at this?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by Benjtalkshow** [comment]
I’d like to help with this.

**Comment by ChrisFernandezVivas** [comment]
Hi I from Dojo Coding

1- I try implement a recursive function for fibonnaci
2- test the script
3- upload the script

thank you so much :)

**Comment by Emmanex01** [comment]
Hi,
May I handle this issue?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects etc  .   please /assign  this issue .
Thank You

**Comment by Michaelkingsdev** [comment]
Could I take over this issue?

**Comment by mimiprosper** [comment]
Can I be assigned to this? Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You
