### ISSUE TITLE
Sum of array elements script in Cairo

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#32]
## Description
- Create a script in Cairo that receives an array and returns the total sum of the elements.

## Steps
- Add a new script in the corresponding directory.

**Comment by SoarinSkySagar** [comment]
May I work on this issue @danielcdz?

My approach: I would create a new function that takes an array as input and returns the sum of all its elements by looping over them.

eta: 1 day

**Comment by aurlic** [comment]
Hello ! I would be thrilled to solve this issue. I have finished School42's common core and  am currently learning Cairo through NodeGuardians and would love to test my skills. 
Thank you in advance !

**Comment by Thibrac** [comment]
I'd love to work on this! i'm a newbee in cairo but i've finish the 42school common core :)

**Comment by omsant02** [comment]
Can I tackle this one?

**Comment by Akshola00** [comment]
I’d love to work on this task.

**Comment by codebestia** [comment]
@danielcdz could i work on this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by emarc99** [comment]
Can I take this from here?
Finished starklings, node guardians quests and basecamp graduate.

**Comment by GideonBature** [comment]
May I take this issue on?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by ShantelPeters** [comment]
Let me handle this issue!
 I will create a new Cairo script in the specified directory that defines a function to compute the sum of an array's elements. nd then use a loop to iterate through the array, adding each element to an accumulator variable, and return the total. 
Lastly i will ensure the script is syntactically correct and follows Cairo conventions.

**Comment by Yunusabdul38** [comment]
I'd like to take this issue.

**Comment by Benjtalkshow** [comment]
Is this issue still available?

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario would love to work on this , my ETA is >8 Hours and ill create a draft PR in 3 hours time. Thank you for this opportunity. :)

**Comment by ChrisFernandezVivas** [comment]
Hi im from dojo coding


steps:

1-declare a function sum_array
2- use for loops for sum each element

thank you

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects etc  .   please /assign  this issue .
Thank You

**Comment by MullerTheScientist** [comment]
please can i handle this issue!

**Comment by Emmanex01** [comment]
Hi,
Can I contribute to this one?

**Comment by DanielEmmanuel1** [comment]
Can I attempt this issue?

I'll write a Cairo script defining a function that takes an array as input, iterates through the elements, and calculates their sum

**Comment by mimiprosper** [comment]
Can I start working on this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You
