### ISSUE TITLE
Maximun in array in Cairo

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#33]
## Summary
- Create a script that returns the maximum number of a given array.
- Store the new script in the corresponding directory.

**Comment by Judah04** [comment]
@danielcdz kindly assign me this issue. As you mentioned in the call yesterday I would like to use contributing to this project to help solidify my understanding of the smart contracts in cairo. And i believe i can handle this issue if am assigned . PR in less than 20hrs.

**Comment by SoarinSkySagar** [comment]
May I work on this issue @danielcdz?

My approach: I would create a new function that takes in an array as input and returns the maximum element within it. 

ETA: 1 day

**Comment by Thibrac** [comment]
Can I attempt this issue? i think it's easy for begin and i'm cairo beginner ;)

**Comment by omsant02** [comment]
Could I grab this task?

**Comment by codebestia** [comment]
Could i work on this?

ETA: 12 hours

**Comment by Akshola00** [comment]
May I handle this issue?

**Comment by Emmanex01** [comment]
I’d like to work on this.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by GideonBature** [comment]
Can this issue be assigned to me please?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by ShantelPeters** [comment]
I'd be happy to do this.

**Comment by Benjtalkshow** [comment]
Let me handle this issue!

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario, would love to work on this , my ETA is >4 Hours and ill create a draft PR in 3 hours time. Thank you for this opportunity. :)

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects etc  .   please /assign  this issue .
Thank You

**Comment by DanielEmmanuel1** [comment]
Mind if I take this issue?

I'll create a script with a func that iterates through the array to find the maximum value, store the script in the designated directory, and ensure it’s reusable.

ETA: 12 hrs

**Comment by GideonBature** [comment]
@danielcdz Will start working on it. Thank you.

**Comment by mimiprosper** [comment]
Can I start working on this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.

**Comment by JoE11-y** [comment]
I'd be happy to do this.
