### ISSUE TITLE
Add a simple smart contract that performs a `hello_world`

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#4]
## Summary
- Follow the [getting started](https://foundry-rs.github.io/starknet-foundry/index.html) section from the SNFoundry book to place the starter contract in `starknet/contracts`.
   - Inside the directory create a new `helloWorld` directory.

**Comment by gadyrcdz** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stark-cairo-nodes).

### My background and how it can be leveraged
A few weeks ago I was working on my first issue and I learned too much from it.

### How I plan on tackling this issue
I was reading and learning about "The Starknet Foundry Book", and I think I can solve this issue.

**Comment by danielcdz** [comment]
@gadyrcdz all yours 🫡

**Comment by Manush-2005** [comment]
Hey @danielcdz , can I take this issue up

**Comment by danielcdz** [comment]
hello @Manush-2005 to submit a PR you first need to have the issue assigned!
