### ISSUE TITLE
Fill guidelines from issues 

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#54]
## Description  

Currently, the Git, Issues, and Contribution guidelines are written as pinned issues in the project’s **Issues** tab. While this is helpful, we want to organize these guidelines into dedicated files within the repository for better accessibility and structure.  

---

## ✅ Steps to Complete  

1. **Extract Content:**  
   - Review the pinned issues in the **Issues** section to gather the relevant content for each guideline.  

2. **Fill the Files:**  
   - Navigate to the `docs/` directory in the repository, where pre-created files for the guidelines already exist.  
   - Populate each file with the corresponding content from the pinned issues.

**Comment by emarc99** [comment]
Can I be assigned to this?

**Comment by Michaelkingsdev** [comment]
@danielcdz 
I am a new contributor to this project. Can i be assigned to this task?

**Comment by mimisavage** [comment]
May I take this issue on ?

**Comment by emarc99** [comment]
Thanks.
