### ISSUE TITLE
Implement script/contract for random number generator 

### ISSUE THREAD

**Issue by coxmars** [KaizeNodeLabs/stark-cairo-nodes#59]
# Implement Random Number Generator

## Objective
Create a script/contract that generates random numbers using different techniques as you decide.

## Techniques to consider for this implementation
- Generator using block hash
- Generator using keccak256
- Combination of multiple entropy sources
- Pragma Verifiable Random Function (VRF): https://docs.pragma.build/v1/Resources/randomness/randomness

## Read for more understanding
- https://starknet-by-example.voyager.online/applications/random_number_generator

## 📜 Additional Notes
⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by aradix16** [comment]
Hi!
I've already contributed to this project during ODHack10 and would love to keep learning Cairo by working on this random number generator implementation. Thanks !  :)

**Comment by manlikeHB** [comment]
Hi, I am a Cairo Developer with great experience contributing to lots of amazing Cairo projects. Can I try solving this issue?

**Comment by petersdt** [comment]
I’d like to help with this.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by aurlic** [comment]
Hey I'm currently learning cairo through Node Guardians and I would love to take on this issue, I think it would be a great match to perfect my skills and improve. Thanks in advance !

**Comment by jaiminRaiyani** [comment]
Can I start working on this?

**Comment by Thibrac** [comment]
I'm making little by little progress on node guardian so it would help me to make this issue to progress!

**Comment by jorgezerpa** [comment]
Hi! Dojo here⛩️

I'm Jorge. I have 4 years of experience in software development and have been contributing to many projects of the Starknet ecosystem. 
I specialized in smart contracts development and testing. 

### How do I plan to tackle the issue?

I will create 4 different functions using different approaches to generate randomness:
- get_random_number_with_block_data: Take numerical properties of the block like the number, timestamp, l1_gas_price, etc. and merge/add to create a random number.   
- get_random_number_with_keccak256: hash some random data (using the same approach as above function) with Keccak-256 and then taking the modulo of the result with the desired range. I will follow this example writted in Solidity adapting it to Starknet https://www.geeksforgeeks.org/random-number-generator-in-solidity-using-keccak256/
- get_random_number_with_user_entropy: Allow the user/app to introduce a series of random number/values. The idea is to receive a series of inputs like year of birth, ID number, random words... and merge it with a random computational entropy source like mouse coords when click the generate button, or disk activity. It means, any kind of computer data that the front app could take and did not depends of the user.  
- get_random_number_with_vrf: This one will connect with Pragma oracle to get a random number following the Pragma docs https://docs.pragma.build/v1/Resources/randomness/randomness


### ETA: 4-5 hours.

I'm attentive🥷

**Comment by Dprof-in-tech** [comment]
Gm chief, I am Dprof-in-tech and i would love to work on this issue. i have had experience working with Cartridge.gg s VRF method and my estimated ETA is 2 days.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by SoarinSkySagar** [comment]
May I work on this issue @danielcdz?

approach: i will use the current blocktimestamp, along with a counter (if possible) to generate a random number using poseidon hash in cairo

eta: 3 days

**Comment by JoE11-y** [comment]
May I take care of this?

**Comment by Michaelkingsdev** [comment]
Could I take a shot at this?

**Comment by Supa-mega** [comment]
Could I take a shot at this?

**Comment by GideonBature** [comment]
Can I try solving this issue?

**Comment by trashcancries** [comment]
May I work on this issue @danielcdz?

eta: 3 days

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contributions on OD(https://app.onlydust.com/u/Bosun-Josh121) looking to make first contribution on this project

How I plan on tackling this issue:

I would Develop a smart contract in Cairo that supports these techniques.
Provide methods for generating and retrieving random numbers using the chosen approaches.
Include safeguards to mitigate manipulation and ensure fair randomness distribution.
Leverage insights from recommended resources to ensure best practices are followed.
This implementation will deliver a robust and flexible random number generation solution suitable for various use cases.

work on feedback & recommendation ensuring contact. Can deliver within a day upon assignment

**Comment by omsant02** [comment]
i would like to take this issue

I'll create a contract that demonstrates multiple randomness techniques:

-Block-hash based generator using block timestamp and caller address for entropy
-Keccak256-based implementation with combined entropy sources
-Integration with Pragma VRF for verifiable randomness (based on the provided documentation at docs.pragma.build)

I'll follow the starknet-by-example format for documentation and include examples for each method.

**Comment by Jagadeeshftw** [comment]
Hello @coxmars ,

I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet.

My Approach:

1. To address the random number generator implementation, I’ll explore different techniques like using block hashes, keccak256, and combining multiple entropy sources.
2.  Additionally, I’ll review Verifiable Random Function (VRF) for ensuring fairness and randomness in the contract.

If it is assigned to me then I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by tasneemtoolba** [comment]
I'm a full-stack developer who recently shifted to web3, and trying so hard to gain experience in smart contracts!! I do a small experience writing smart contracts in Solidity and Cairo!, looking forward to work on this task!!

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

Kindly assign me please, I'm up for the task.

**Comment by ikezuby2012** [comment]
I'd love to give this a go.

**Comment by suhas-sensei** [comment]
I’d like to resolve this. I'll implement a comprehensive random number generator using multiple entropy sources and Pragma VRF integration on Starknet. 
Having worked with writing cairo contracts and cryptographic primitives, I'll ensure secure and verifiable random number generation while providing multiple implementation options.

**Comment by michojekunle** [comment]
I’m interested in this one.

**Comment by Nityam573** [comment]
I'd be happy to do this.
How do I plan to tackle the issue?
I will create 4 different functions using different approaches to generate randomness:
1. Using Block Hash
Generate randomness based on the current block hash, combining it with sender details or a nonce.
2.  Keccak256-Based Generator
Hash multiple unpredictable inputs to create pseudo-randomness.
3. . Combination of Multiple Entropy Sources
Combine various entropy sources to reduce predictability.
4.  Pragma Verifiable Random Function (VRF)
Use Pragma VRF for secure and verifiable randomness.

**Comment by 0xprivateChaos** [comment]
Hi, I'm Aman, and I'd like to work on this issue.

My plan:

1. Implement random number generation using block hash and keccak256.
2. Combine multiple entropy sources for improved randomness.
3. Integrate a Verifiable Random Function (VRF) for secure and unbiased randomness.
4. Ensure modularity for adding new techniques easily in the future.

**Comment by ekumamatthew** [comment]
Let me try this one!

**Comment by blessingbytes** [comment]
i would to tackle this issue.

**Comment by olisaagbafor** [comment]
May I pick this up?

**Comment by Dorcas18** [comment]
May I take this issue on?

**Comment by DADADAVE80** [comment]
Is this issue still available?

**Comment by sandragcarrillo** [comment]
Can I handle this task?

**Comment by sandragcarrillo** [comment]
Hi, I would love to get assigned to this issue.

I have been learning Cairo for the past 4 months, learning while writing technical content useful for other new devs. This would be an amazing opportunity to keep improving my skills.

ETA: 1-2 days

**Comment by jorgezerpa** [comment]
🚀🚀
