### ISSUE TITLE
Add MD file with instructions about how to deploy on Remix IDE

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#62]
## 📄 Description  
Create a comprehensive guide for deploying smart contracts in [Remix IDE](https://remix.ethereum.org/). The guide must include steps to install the Starknet plugin, compile contracts, deploy using Remix's wallet or predefined wallets, and provide beginner-friendly, detailed instructions. Add the guide as an `.md` file (`DEPLOYMENT_GUIDE.md`) in the directory of an existing contract from the repository.  

## ✅ Acceptance Criteria  
1. **Guide Structure**:  
   - Markdown file with a table of contents.  

2. **Content Coverage**:  
   - Steps for installing the Starknet plugin.  
   - Instructions for compiling contracts.  
   - Detailed deployment process, including wallet setup and usage.  

3. **Example**:  
   - Deployment example using a contract from the repository.  

4. **Clarity**:  
   - Beginner-friendly language, visuals, and troubleshooting tips.  

5. **Validation**:  
   - Instructions are tested and referenced in the repository's root README.

## 📜 Additional Notes
⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by Emmanex01** [comment]
I'd love to give this a go.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in creating and maintaining clear and user-friendly documentation..

ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by NueloSE** [comment]
Can I start working on this?

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by Supa-mega** [comment]
Can I be assigned to this?

**Comment by Akshola00** [comment]
Would love to tackle this!

**Comment by zanastas** [comment]
Excited to contribute to this task! I’ve written several GitHub documentations for EthGlobal hackathons and recently published a blog post on “Getting Started with Semaphore,” which provides step-by-step instructions for setting up a new project and references to resources. Feel free to check it out [here](https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8)

**Comment by ShantelPeters** [comment]
I'd like to handle this task.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by salazarsebas** [comment]
Hi stark-cairo-nodes,

# My background

I'm Sebastian, software engineer 👨🏻‍💻 and part of the Dojo Coding ⛩️ community, and I would like to contribute to this issue. I have experience with different technologies and I have worked on some projects through OnlyDust and I like to contribute to help the projects.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Research on how to implement the starknet plugin, document it.
- Create a markdown file DEPLOYMENT_GUIDE.md where I will place the documentation.
- Compile contracts and deploy using the wallet.
- Verify that the tests are working correctly.
- Send a pr pending feedback.

**Comment by tasneemtoolba** [comment]
can I take this issue?
