### ISSUE TITLE
Add section in readme to check .tool-versions for each contract/script

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#69]
## 📄 Description  
- Each script or contract in the repository includes a `.tool-versions` file, which specifies the required versions of dependencies needed to run or compile the Cairo files. However, this information is not currently explained in the README.  
- The goal of this issue is to add a general section in the README to inform users about the purpose and usage of the `.tool-versions` file with **asdf**. This will help users understand its importance and ensure they have the correct dependencies installed.  

### Scope of Work
1. Add a concise explanation of the `.tool-versions` file and its role in managing dependency versions.  
2. Provide an example of how the file looks.  
3. Include an example of the error or warning **asdf** generates when attempting to compile a Cairo file with incorrect dependency versions.  

## ✅ Acceptance Criteria  
- The README contains a new section detailing:  
  - The purpose of the `.tool-versions` file.  
  - How it integrates with **asdf** to manage dependencies.  
  - An example file and common errors or warnings related to incorrect versions.  

## 📜 Additional Notes
⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by raizo07** [comment]
Let me try this one! I'm a Software developer with over 3 years experience

**Comment by wheval** [comment]
I’m interested in this one. Can i work on this?

**Comment by Michaelkingsdev** [comment]
I’d love to work on this task.

**Comment by 3th-Enjay** [comment]
Can I start working on this?

**Comment by Akshola00** [comment]
I'd love to give this a go.
I'm confident I can hadle this 
eta 1 day

**Comment by zanastas** [comment]
Excited to contribute to this task! I’ve written several GitHub documentations for EthGlobal hackathons and recently published a blog post on “Getting Started with Semaphore,” which provides step-by-step instructions for setting up a new project and references to resources. Feel free to check it out [here](https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8)

**Comment by wheval** [comment]
Thank you!
