### ISSUE TITLE
Create template for PRs in .github directory

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#7]
## Description
We want a template that automatically appears when creating a new PR. To do this, add a properly named MD file to the .github directory.
  - Create a new directory inside .github called `PULL_REQUEST_TEMPLATE`
  - Create a proper template using markdown that includes a base to be filled by those who propose a PR.

**Comment by MariangelaNM** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stark-cairo-nodes).

### My background and how it can be leveraged
I’m a Computer Engineer, and I’d be thrilled to have the opportunity to help resolve this issue and contribute to your fantastic project.

### How I plan on tackling this issue
1. Create the folder `.github/PULL_REQUEST_TEMPLATE`.
2. Inside, create a `template.md` file.
3. Add the template content.

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stark-cairo-nodes).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun & Scaffold Stark.

### How I plan on tackling this issue
My Approach includes:
- I will thoroughly read the current documentation on creating PR for open-source projects and projects on the OnlyDust Platform.
- Write the template for creating Pull Requests.
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the Review of the PR
