### ISSUE TITLE
Add cargo installation dependencies for scripts and contracts in readme

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#71]
## 📄 Description  
- In some cases, using **Scarb** requires **Cargo** to be installed. However, this prerequisite is not currently defined in our instructions for scripts and contracts.  
- The goal of this issue is to include clear and detailed instructions on how to install Cargo, referencing the official guide: [Cargo Installation Guide](https://doc.rust-lang.org/cargo/getting-started/installation.html).

## ✅ Acceptance Criteria  
- The **README** includes updated sections for both **scripts** and **contracts**, detailing:  
  - The need for Cargo as a dependency.  
  - Step-by-step instructions for installing Cargo.  
  - Links to relevant resources, such as the official Cargo installation guide.  

## 📜 Additional Notes
⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a smart contract developer with expertise in StarkNet and Cairo. After completing the Cairo Basecamp, I gained a solid understanding of decentralized applications and have contributed to several projects on OnlyDust, where I focused on smart contract development and optimization using Cairo.

I would be happy to help resolve this issue by updating the README with clear and detailed instructions for installing Cargo. With my experience in creating documentation, I am confident I can provide comprehensive, step-by-step guidance for both scripts and contracts, referencing the official Cargo Installation Guide. Please assign me this task—I look forward to contributing to the project!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days.

**Comment by raizo07** [comment]
I'd love to give this a go. I'm a Software developer with over 3 years experience

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by CollinsC1O** [comment]
Hello @danielcdz I'm a front-end and a blockchain developer, I write cairo and I will love to work on this. Please assign

**Comment by zanastas** [comment]
Excited to contribute to this task! I’ve written several GitHub documentations for EthGlobal hackathons and recently published a blog post on “Getting Started with Semaphore,” which provides step-by-step instructions for setting up a new project and references to resources. Feel free to check it out [here](https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8)

**Comment by ShantelPeters** [comment]
Let me try this one!
