### ISSUE TITLE
Fix simple counter contract not compiling

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#72]
## Description
- The [Simple Counter Contract](https://github.com/KaizeNodeLabs/stark-cairo-nodes/tree/main/starknet/contracts/simple_counter) is currently failing to compile, likely due to missing or incorrect tags in the scarb.toml file.
- This issue must be resolved to ensure functionality so that the contract can be successfully compiled and deployed in future steps.

## Acceptance criteria
- The command scarb build runs successfully and the contract can be compiled.

## 📜 Additional Notes
⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by aurlic** [comment]
Hey I would love to tackle this issue, I have been learning cairo through node guardians and I think that it would be a great occasion to practice !

**Comment by Thibrac** [comment]
To continue contributing to this great project, I propose to fix this bug. I'm trying to make progress during my studies ! :)

**Comment by ChrisFernandezVivas** [comment]
hi, im from Dojo coding , my ETA is 2 hours

how to solve?

1- read the another code
2- search de bug
3- fix the bug
4-try if compile well
5- pull request

**Comment by Dprof-in-tech** [comment]
Good day sir, i am Dprof-in-tech and i would love to work on this issue. I have extensive experience working on cairo contracts and my ETA would be 2 days tops.

**Comment by codebestia** [comment]
@danielcdz  Can i tackle this?
I am blockchain developer with adequate experience in building blockchain application for several chains. I expertise mainly with rust, cairo and solidity but i still dabble with trending technologies.

To handle this task, i will troubleshoot the `scarb.toml` file thorougly and find the underlying issue
I will open a PR as soon as possible.

**Comment by jaiminRaiyani** [comment]
Let me handle this issue!

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by Emmanex01** [comment]
Could I try solving this?

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 

If assigned this i would complete it within 2 days.

**Comment by GideonBature** [comment]
Could I take a shot at this?

My name is Gideon Bature, a Software Engineer, I have experience working with Cairo, I am also excellent at tracing and fixing bugs. If given the opportunity, I will send my first PR within 48 hours.

Thank you!

**Comment by SoarinSkySagar** [comment]
May I work on this issue @danielcdz?

eta: 3 days

**Comment by NowGoody** [comment]
Is it okay if I tackle this?

**Comment by tasneemtoolba** [comment]
can I work on this issue? ETA: 1 day

**Comment by Michaelkingsdev** [comment]
Can I work on this, please?

**Comment by Supa-mega** [comment]
I’d like to help with this.

**Comment by emarc99** [comment]
let me do this, ETA -2 days, will test after completion.

**Comment by zintarh** [comment]
Could I take on this issue?

**Comment by Joewizy** [comment]
Let me handle this issue!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I can fix the compilation issue in the Simple Counter Contract by updating the scarb.toml file with the correct tags, ensuring it compiles successfully with the scarb build command. Please assign this issue to me.

Thank you!

**Comment by zanastas** [comment]
I would like to apply for this task! I just finished the Starkling Coding Camp with HerDAO and I’m excited to put what I’ve learned into practice. This task feels like a nice step toward growing as a Cairo developer.

**Comment by FemiOje** [comment]
gm. I'm jinius, a cairo dev looking to gain more experience in this ODHack.

How I plan on tackling this issue:
1. Fork the repo, clone and create a branch for the fix.
2. Add the following missing tags to the scarb.toml at stark-cairo-nodes/starknet/contracts:
[dependencies]
starknet = "2.8.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.32.0" }
assert_macros = "2.8.4"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
3. Run `scarb build` and ensure and ensure the contract runs and does not break.
4. Create pull reruest and submit.

thanks for the opportunity 💪

**Comment by trashcancries** [comment]
May I work on this issue @danielcdz?

eta: 3 days

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by Emrys02** [comment]
## Hi @danielcdz Can I pick this up?

### Steps To Resolve Issue

1. ***Run scarb build*** to get more details on the error
2. Use details gotten from the error to address the issue
3. Attempt building to confirm error has been resolved

In addition to the above, I'll also maintain steady communication on the progress of the task.

**Comment by omsant02** [comment]
i would like to solve this issue

My approach to solve this issue is by adding a dependencie "starknet = ">=2.3.1"" under dependencies section in scarb.toml

ETA : 10 mins

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
I have solid experience in both web2 and web3 and have contributed to open-source projects that ended up being merged
will be glad to work on this as my first contribution to this project
