### ISSUE TITLE
Create template for new issues description in .github

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#8]
## Description
We want to have a template that automatically appears when creating a new issue. This can be done by adding a proper-named MD file to the .github directory.
  - Create a new directory inside .github called `ISSUE_TEMPLATE`
  - Create a proper template using markdown that includes a base to be filled by those who propose an issue.

**Comment by diegoTech14** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stark-cairo-nodes).

### My background and how it can be leveraged
Hello @danielcdz,

I'm a software engineer from Costa Rica and a member of Dojo Coding. I'd love to get the opportunity to help for this issue and contribute to your amazing project.

### How I plan on tackling this issue
I have some experience documenting projects and my step by step to solve it looks like this:
1. I will search and design a cool issue template
2. Create a new directory inside .github called "ISSUE_TEMPLATE"
3. create a template according to the requirements

Looking forward to hearing from you!

Best regards, 

Diego Duarte Fernández.

**Comment by danielcdz** [comment]
@diegoTech14 go ahead! 🫡
